<div class="header">  
	 <div class="container">
		  <div class="logo">
			  <a href="index.php?page=home"><img src="public/images/logo.jpg" title="" /></a>
		  </div>
			 <!---start-top-nav---->
			 <div class="top-menu">
				 <!-- <div class="search">
					 <form>
					 <input type="text" placeholder="" required="">
					 <input type="submit" value=""/>
					 </form>
				 </div> -->
				  <span class="menu"> </span> 
				   <ul>
						<li class="active"><a href="index.php?page=home">HOME</a></li>
						<li><a href="index.php?page=login">SE CONNECTER</a></li>
						<li><a href="index.php?page=register">S'ENREGISTRER</a></li>
						<div class="clearfix"> </div>
				 </ul>
			 </div>
			 <div class="clearfix"></div>
					<script>
					$("span.menu").click(function(){
					$(".top-menu ul").slideToggle("slow" , function(){
					});
					});
					</script>
				<!---//End-top-nav---->					
	 </div>
</div>