<div class="contact-content">
	 <div class="container">
		     <div class="contact-info">
			 <h2>ENREGISTREZ VOUS</h2>
			 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Contrary to popular belief.</p>
		     </div>
			 <div class="contact-details">				 
			 <form method="post">
				 <input type="text" name="pseudo" placeholder="Pseudo" required/>
				 <input type="email" name="mail" placeholder="Email" required/>
				 <input type="password" name="pass1" placeholder="Password 1" required/>
				 <input type="password" name="pass2" placeholder="Password 2" required/>
				 <button type="submit" name="subscribe">S'INSCRIRE</button>
			 </form>
		  </div>
	 </div>
</div>