<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title><?= $page ?></title>
		<link rel="stylesheet" type="text/css" href="public/styles/reset.css">
		<link rel="stylesheet" type="text/css" href="public/styles/style.css">
		<link rel="stylesheet" type="text/css" href="public/font-awesome/css/font-awesome.min.css">
	</head>
	<body>
		<?php
			require("controller/header.php");

			require("controller/content.php");

			require("controller/footer.php");
		?>
		<script src="public/js/jquery.min.js"></script>
		<script src="public/js/bootstrap.min.js"></script>
	</body>
</html>


